### PR TITLE
updated deprecated dependencies

### PR DESCRIPTION
**Pull request by johnanisere**

### CODE REVIEW

**Comment by jihdeh** [comment]
That's not all, 
run `npm outdated` in your terminal to see the packages that need updating.

**Comment by jihdeh** [comment]
Hold on before upgrading the other packages, there are major changes.

**Comment by johnanisere** [comment]
ok

On Fri, Apr 13, 2018 at 8:39 AM, Babajide Fowotade <notifications@github.com

**Comment by jihdeh** [comment]
Sups. have a look at these updates.
https://github.com/jihdeh/quick-server/pull/1/files
and
https://github.com/jihdeh/quick-server/pull/3/files
...
The backend uses this boilerplate I created, I have updated the boilerplate to conform to latest changes. 
Follow those PR changes to update the backend you're working on. and update your PR.
Make sure when you visit, http://localhost:6500/api/message, you see a json message.

**Comment by johnanisere** [comment]
oh ok..I'm working on it now

On Fri, Apr 13, 2018 at 7:22 PM, Babajide Fowotade <notifications@github.com

**Comment by johnanisere** [comment]
How about mocha and supertest, they are still outdated. Should I updated
them?

**Pull request closed without merging**
